name: "Bambu Lab P1 - Obico ML Server"
description: "My first real add-on!"
version: "1.0.0"
slug: "bambu_lab_p1_spaghetti_detection"
init: false
arch:
  - amd64
startup: services
ports:
  3333/tcp: 3333
options:
  obico_api_secret: "obico_api_secret"
schema:
  obico_api_secret: str